Document: sbs
Title: Debian sbs Manual
Author: <insert document author here>
Abstract: This manual describes what sbs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sbs/sbs.sgml.gz

Format: postscript
Files: /usr/share/doc/sbs/sbs.ps.gz

Format: text
Files: /usr/share/doc/sbs/sbs.text.gz

Format: HTML
Index: /usr/share/doc/sbs/html/index.html
Files: /usr/share/doc/sbs/html/*.html

  
